### ISSUE TITLE
Html problem on wordpress

### ISSUE THREAD

**Issue by NeoCsatornaja** [brightcove/videojs-urlparams#7]
If I use this link on my website:

``` html
<a href="?t=30s&autoplay">seek to 30 seconds and autoplay</a>
```

I get the post url and this, so when I sended a comment I get(example) this link:

http://www.neocsatblog.mblx.hu/sajat-szinkront-csinaltam/?t=30s&autoplay

And if you click this link the page reload, and nothing happening :(

**Comment by bcjwilson** [comment]
It looks like your page is using an iframe to load the video:

``` html
<iframe allowfullscreen="" webkitallowfulslcreen="" src="http://neocsatblog.mblx.hu/embeds/ezekiel.html" style="width:661px;height:286px;border:none;overflow:hidden;"></iframe>
```

When the videojs-urlparams plugin looks at `window.location.href` for the URL, it sees `http://neocsatblog.mblx.hu/embeds/ezekiel.html`. This URL doesn't have the `t=` or `autoplay` attributes, which is why it doesn't do anything.

You need to append the parameters to the iframe's `src` URL. Hope this helps!

**Comment by NeoCsatornaja** [comment]
Not really :(
Because this time not constancy.
I would like to use this in comment form, that if a user give a time code, another user can see this and click for it.
Example:
-"See what happening:(--->this is a timelink) 1:22"
- "Whao, awsome!"
